#include <vector>

#define VK_NO_PROTOTYPES
#define VK_ENABLE_BETA_EXTENSIONS
#include <vulkan/vulkan.h>

// Should keep sync with optional_device_exts inside hwcontext_vulkan.c (n7.1.1)
extern const std::vector<const char *> optional_device_exts = {
    /* Misc or required by other extensions */
    VK_KHR_PORTABILITY_SUBSET_EXTENSION_NAME,
    VK_KHR_PUSH_DESCRIPTOR_EXTENSION_NAME,
    VK_EXT_DESCRIPTOR_BUFFER_EXTENSION_NAME,
    VK_EXT_PHYSICAL_DEVICE_DRM_EXTENSION_NAME,
    VK_EXT_SHADER_ATOMIC_FLOAT_EXTENSION_NAME,
#if defined(VK_KHR_COOPERATIVE_MATRIX_EXTENSION_NAME)
    VK_KHR_COOPERATIVE_MATRIX_EXTENSION_NAME,
#endif
    VK_NV_OPTICAL_FLOW_EXTENSION_NAME,
#if defined(VK_EXT_SHADER_OBJECT_EXTENSION_NAME)
    VK_EXT_SHADER_OBJECT_EXTENSION_NAME,
#endif
#if defined(VK_KHR_VIDEO_MAINTENANCE_1_EXTENSION_NAME)
    VK_KHR_VIDEO_MAINTENANCE_1_EXTENSION_NAME,
#endif

    /* Imports/exports */
    VK_KHR_EXTERNAL_MEMORY_FD_EXTENSION_NAME,
    VK_EXT_EXTERNAL_MEMORY_DMA_BUF_EXTENSION_NAME,
    VK_EXT_IMAGE_DRM_FORMAT_MODIFIER_EXTENSION_NAME,
    VK_KHR_EXTERNAL_SEMAPHORE_FD_EXTENSION_NAME,
    VK_EXT_EXTERNAL_MEMORY_HOST_EXTENSION_NAME,
#if defined(VK_KHR_EXTERNAL_MEMORY_WIN32_EXTENSION_NAME)
    VK_KHR_EXTERNAL_MEMORY_WIN32_EXTENSION_NAME,
#endif
#if defined(VK_KHR_EXTERNAL_SEMAPHORE_WIN32_EXTENSION_NAME)
    VK_KHR_EXTERNAL_SEMAPHORE_WIN32_EXTENSION_NAME,
#endif

    /* Video encoding/decoding */
    VK_KHR_VIDEO_QUEUE_EXTENSION_NAME,
    VK_KHR_VIDEO_ENCODE_QUEUE_EXTENSION_NAME,
    VK_KHR_VIDEO_DECODE_QUEUE_EXTENSION_NAME,
#if defined(VK_KHR_VIDEO_ENCODE_H264_EXTENSION_NAME)
    VK_KHR_VIDEO_ENCODE_H264_EXTENSION_NAME,
#endif
    VK_KHR_VIDEO_DECODE_H264_EXTENSION_NAME,
#if defined(VK_KHR_VIDEO_ENCODE_H265_EXTENSION_NAME)
    VK_KHR_VIDEO_ENCODE_H265_EXTENSION_NAME,
#endif
    VK_KHR_VIDEO_DECODE_H265_EXTENSION_NAME,
#if defined(VK_KHR_VIDEO_DECODE_AV1_EXTENSION_NAME)
    VK_KHR_VIDEO_DECODE_AV1_EXTENSION_NAME,
#endif
};
